<a href="https://colab.research.google.com/github/Dhanushgowda2342/AIML-journey/blob/main/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
x = np.array([[1,1],
             [2,3],
              [3,2]])
print(x.shape)

(3, 2)


In [7]:
mean = np.mean(x,axis=0)
mean


array([2., 2.])

In [9]:
x_centered = x - mean
x_centered

array([[-1., -1.],
       [ 0.,  1.],
       [ 1.,  0.]])

In [11]:
cov_matrix = np.cov(x_centered,rowvar=False)
cov_matrix

array([[1. , 0.5],
       [0.5, 1. ]])

In [12]:
eigen_values,eigen_vector = np.linalg.eigh(cov_matrix)
eigen_values,eigen_vector

(array([0.5, 1.5]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [14]:
best_direction = np.argmax(eigen_values)